[package]
edition = "2021"
name = "macerator"
version = "0.1.0"

[features]
default = ["std"]

std = []

[dependencies]
paste = "1"
pulp = { git = "https://github.com/wingertge/pulp.git", rev = "b162d37dd53b6209fc038829cd416736ebfba53b", default-features = false }
# pulp = { path = "../pulp/pulp" }
