name: Rust loongarch64 QEMU

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: sandervocke/setup-qemu-container@v1
      with:
        container: cr.loongnix.cn/library/debian:buster
        arch: loong64
    - name: Check arch
      shell: run-in-container.sh {0}
      run: |
        echo "Arch in container: $(uname -m)"
    - name: Install Nightly
      shell: run-in-container.sh {0}
      run: rustup install nightly
    - name: Build
      shell: run-in-container.sh {0}
      run: cargo +nightly build --verbose --features nightly
    - name: Run tests
      shell: run-in-container.sh {0}
      run: cargo +nightly test --verbose --features nightly
