name: Rust Stable

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v4
    - name: Update
      run: rustup update
    - name: Build
      run: cargo build --verbose
    - name: Check without default features
      run: |
        cargo check --all-targets --no-default-features
        cargo check --all-targets --no-default-features --features std
    - name: Check no_std target
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add thumbv7em-none-eabihf
        cargo check --no-default-features --target thumbv7em-none-eabihf
    - name: Run tests
      run: cargo test --verbose
